

server:
  port: 8080
  servlet:
    session:
      timeout: 1
#springboot的数据源配置
#1.mysql配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travel
    username: root
    password:
#redis配置
  redis:
    database: 0
    host: 192.168.254.100       #redis服务器地址
    port: 6379                  #redis服务器连接端口
    password:                   #redis服务器连接密码（默认为空）
    pool:
      max-active: 200         #连接池最大连接数(使用负值表示没有限制)
      max-idle: 10            #连接池中最大空闲数
      min-idle: 0             #连接池中最小空闲数
      max-wait: -1            #连接池最大阻塞等待事件（使用负值表示没有限制）
      timeout: 1000             #连接超时时间（毫秒）
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    #是否将sql打印在控制面板(该配置会将sql语句和查询的结果打印在控制台)
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



